# Generated by Django 3.0.1 on 2020-02-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_category',
            options={'verbose_name_plural': 'Blog_categories'},
        )
    ]