# Generated by Django 3.0.8 on 2020-08-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200807_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]