# Generated by Django 3.0.8 on 2020-08-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200807_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]