# Generated by Django 3.0.8 on 2020-09-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
