# Generated by Django 3.2 on 2023-06-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clwbawdio', '0002_auto_20230604_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clwb',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Clwb',
        ),
    ]
